services:
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/yandex_music
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    volumes:
      - ./backend/yandex_music:/app
